#!/usr/bin/env bash

clear ;

IM=$(uname -a)

echo -e " \n "
read -p "Digite seu Nome: " NOME
echo -e " \n "
read -p "Digite sua idade: " IDADE
echo -e " \n "

if [ "$UID" -eq "0" ]; then
    uid="Root"
else
    uid="Comum"
fi

echo -e " Olá $NOME , é um prazer lhe conhecer! \n Você tem $IDADE anos, tá velinho em! \n"
echo -e " Usuário: $USER \n Home: $HOME \n Shell: $SHELL \n Usuário: $uid \n Informações da máquina: $IM \n"